PREFIX void:    <http://rdfs.org/ns/void#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>

SELECT ?type ?resource ?resourceLabel WHERE {
  VALUES ?provider {
    <https://search.data.enanomapper.net/>
    <https://search.data.enanomapper.net/closed/>
  }
  ?provider a void:DatasetDescription ;
    dcterms:title|dc:title ?providerLabel .
  ?resource dc:source ?provider ; a / rdfs:label ?type ;
    rdfs:label ?resourceLabel .
} ORDER BY ASC(?type) ASC(?resource)
