PREFIX sbd:     <https://www.sbd4nano.eu/rdf/#>
PREFIX sbdbel:  <https://www.sbd4nano.eu/bel/#>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?category ?term (COUNT(DISTINCT ?relation) AS ?count)
WHERE {
  ?relation a sbdbel:CausalAssertion ;
    sbdbel:outcome ?outcome .
  ?outcome sbdbel:term ?term ;
       sbdbel:termCat ?category .
} GROUP BY ?category ?term
  ORDER BY DESC(?count)
