#+ endpoint: https://sbd4nanolandscape.rdf.bigcat-bioinformatics.org/sparql
#+ endpoint_in_url: False
#+ enumerate:
#+   - lang:
#+     - en,en


PREFIX npo: <http://purl.bioontology.org/ontology/npo#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sbd:     <https://www.sbd4nano.eu/rdf/#>
PREFIX sbdbel:  <https://www.sbd4nano.eu/bel/#>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/> 
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#> 

SELECT ?materialIRI (SAMPLE(?material_) AS ?material) ?dataset ?datasetLabel
WHERE {
  VALUES ?superclass { npo:NPO_1892 }
  VALUES ?type { sbd:Dataset sbd:Database }
  ?dataset sbdbel:NP ?materialIRI ; a ?type ; rdfs:label ?datasetLabel .
  ?materialIRI rdfs:subClassOf* ?superclass ; rdfs:label ?material_ .
} GROUP BY ?materialIRI ?dataset ?datasetLabel
  ORDER BY ?dataset

