#+ endpoint: https://sbd4nanolandscape.rdf.bigcat-bioinformatics.org/sparql
#+ endpoint_in_url: False
#+ enumerate:
#+   - lang:
#+     - en,en


PREFIX void:    <http://rdfs.org/ns/void#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>

SELECT ?resource ?resourceLabel ?img WHERE {
  ?void a void:DatasetDescription ;
    dcterms:title|dc:title ?resourceLabel .
  OPTIONAL { ?void dc:source ?resource }
  OPTIONAL { ?void foaf:img ?img }
}

