#+ endpoint: https://sbd4nanolandscape.rdf.bigcat-bioinformatics.org/sparql
#+ endpoint_in_url: False
#+ enumerate:
#+   - lang:
#+     - en,en


PREFIX sbd:  <https://www.sbd4nano.eu/rdf/#>
PREFIX sbdbel:  <https://www.sbd4nano.eu/bel/#>
PREFIX enm:     <http://purl.enanomapper.org/onto/>
PREFIX npo: <http://purl.bioontology.org/ontology/npo#>
PREFIX sio: <http://semanticscience.org/resource/SIO_>
PREFIX sbdbel2:  <https://h2020-sbd4nano.github.io/sbdbel/>

SELECT DISTINCT
  ?nm (SAMPLE(?nmLabel_) AS ?nmLabel)
  (COUNT(DISTINCT ?relation) AS ?relations)
WHERE {
  VALUES ?ca { sbdbel:CausalAssertion sbd:CausalAssertion sbdbel2:CausalAssertion }
  VALUES ?nm { enm:ENM_9000077 }
  ?nm rdfs:label ?nmLabel_ .
  OPTIONAL { ?relation a ?ca ; sbdbel:NP | sio:000332 | sbdbel2:NP ?nm . }
} GROUP BY ?superclass ?nm

